<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VzninxDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VzninxD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VzninxD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'microsoftIntegration' => ['privates', 'Webkul\\UVDesk\\CoreFrameworkBundle\\Services\\MicrosoftIntegration', 'getMicrosoftIntegrationService', false],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
            'userService' => ['services', 'user.service', 'getUser_ServiceService', false],
        ], [
            'entityManager' => '?',
            'microsoftIntegration' => 'Webkul\\UVDesk\\CoreFrameworkBundle\\Services\\MicrosoftIntegration',
            'translator' => '?',
            'userService' => '?',
        ]);
    }
}
