<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Diu05WvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.diu05Wv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.diu05Wv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailboxService' => ['privates', 'Webkul\\UVDesk\\MailboxBundle\\Services\\MailboxService', 'getMailboxServiceService', false],
        ], [
            'mailboxService' => 'Webkul\\UVDesk\\MailboxBundle\\Services\\MailboxService',
        ]);
    }
}
