<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1hkzPeNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1hkzPeN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1hkzPeN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'container' => ['services', 'service_container', 'getServiceContainerService', true],
            'quickActionButtonCollection' => ['privates', 'Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection', 'getQuickActionButtonCollectionService', false],
        ], [
            'container' => '?',
            'quickActionButtonCollection' => 'Webkul\\UVDesk\\CoreFrameworkBundle\\Tickets\\QuickActionButtonCollection',
        ]);
    }
}
