<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dbjn_BSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Dbjn.bS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dbjn.bS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'container' => ['services', 'service_container', 'getServiceContainerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'fileSystem' => ['services', 'uvdesk.core.file_system.service', 'getUvdesk_Core_FileSystem_ServiceService', false],
            'passwordEncoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
        ], [
            'container' => '?',
            'entityManager' => '?',
            'eventDispatcher' => '?',
            'fileSystem' => '?',
            'passwordEncoder' => '?',
        ]);
    }
}
