<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgentActivityRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\CoreFrameworkBundle\Repository\AgentActivityRepository' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Repository\AgentActivityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/LazyServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Repository/AgentActivityRepository.php';

        return $container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Repository\\AgentActivityRepository'] = new \Webkul\UVDesk\CoreFrameworkBundle\Repository\AgentActivityRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
