<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\AutomationBundle\Form\DefaultForm' shared autowired service.
     *
     * @return \Webkul\UVDesk\AutomationBundle\Form\DefaultForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Form/DefaultForm.php';

        return $container->privates['Webkul\\UVDesk\\AutomationBundle\\Form\\DefaultForm'] = new \Webkul\UVDesk\AutomationBundle\Form\DefaultForm();
    }
}
