<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_FixturesLoadCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures_load_command' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Command/DoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Command/CommandCompatibility.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Command/LoadDataFixturesDoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/DataFixtures/AddFixtureImplementation.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Loader/SymfonyBridgeLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Fixture.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/AppFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Fixtures/AgentGroups.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Fixtures/AgentPrivileges.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Fixtures/EmailTemplates.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Fixtures/HelpdeskBranding.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Fixtures/TicketPriorities.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Fixtures/TicketStatuses.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Fixtures/TicketTypes.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Fixtures/UserRoles.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Fixtures/AutomationWorkflowFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/support-center-bundle/Fixtures/KnowledgebaseWebsite.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Purger/PurgerFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Purger/ORMPurgerFactory.php';

        $a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);
        $a->addFixtures([0 => ['fixture' => new \App\DataFixtures\AppFixtures(), 'groups' => []], 1 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\AgentGroups(), 'groups' => []], 2 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\AgentPrivileges(), 'groups' => []], 3 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\EmailTemplates(), 'groups' => []], 4 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\HelpdeskBranding(), 'groups' => []], 5 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\TicketPriorities(), 'groups' => []], 6 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\TicketStatuses(), 'groups' => []], 7 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\TicketTypes(), 'groups' => []], 8 => ['fixture' => new \Webkul\UVDesk\CoreFrameworkBundle\Fixtures\UserRoles(), 'groups' => []], 9 => ['fixture' => new \Webkul\UVDesk\AutomationBundle\Fixtures\AutomationWorkflowFixtures(), 'groups' => []], 10 => ['fixture' => new \Webkul\UVDesk\SupportCenterBundle\Fixtures\KnowledgebaseWebsite(), 'groups' => []]]);

        $container->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($container->services['doctrine'] ?? $container->getDoctrineService()), ['default' => new \Doctrine\Bundle\FixturesBundle\Purger\ORMPurgerFactory()]);

        $instance->setName('doctrine:fixtures:load');

        return $instance;
    }
}
