<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\ExceptionSubscriber' shared autowired service.
     *
     * @return \App\EventListener\ExceptionSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/ExceptionSubscriber.php';

        $a = ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService());

        if (isset($container->privates['App\\EventListener\\ExceptionSubscriber'])) {
            return $container->privates['App\\EventListener\\ExceptionSubscriber'];
        }

        return $container->privates['App\\EventListener\\ExceptionSubscriber'] = new \App\EventListener\ExceptionSubscriber($a, $container);
    }
}
