<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImageCache\ImageManager' shared autowired service.
     *
     * @return \App\Controller\ImageCache\ImageManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/intervention/image/src/Intervention/Image/ImageManager.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ImageCache/ImageManager.php';

        return $container->services['App\\Controller\\ImageCache\\ImageManager'] = new \App\Controller\ImageCache\ImageManager($container);
    }
}
