<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicrosoftAppsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\CoreFrameworkBundle\Controller\Microsoft\MicrosoftApps' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Controller\Microsoft\MicrosoftApps
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Controller/Microsoft/MicrosoftApps.php';

        $container->services['Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Microsoft\\MicrosoftApps'] = $instance = new \Webkul\UVDesk\CoreFrameworkBundle\Controller\Microsoft\MicrosoftApps();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Microsoft\\MicrosoftApps', $container));

        return $instance;
    }
}
