<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailboxChannelXHRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\MailboxBundle\Controller\MailboxChannelXHR' shared autowired service.
     *
     * @return \Webkul\UVDesk\MailboxBundle\Controller\MailboxChannelXHR
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/mailbox-component/Controller/MailboxChannelXHR.php';

        $container->services['Webkul\\UVDesk\\MailboxBundle\\Controller\\MailboxChannelXHR'] = $instance = new \Webkul\UVDesk\MailboxBundle\Controller\MailboxChannelXHR(($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['Webkul\\UVDesk\\MailboxBundle\\Services\\MailboxService'] ?? $container->getMailboxServiceService()), ($container->services['translator'] ?? $container->getTranslatorService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\MailboxBundle\\Controller\\MailboxChannelXHR', $container));

        return $instance;
    }
}
