<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrateDatabaseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Console\Wizard\MigrateDatabase' shared autowired service.
     *
     * @return \App\Console\Wizard\MigrateDatabase
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Console/Wizard/MigrateDatabase.php';

        return $container->services['console.command.public_alias.App\\Console\\Wizard\\MigrateDatabase'] = new \App\Console\Wizard\MigrateDatabase($container, ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
