<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPackageCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\ExtensionFrameworkBundle\Utils\PackageCollection' shared autowired service.
     *
     * @return \Webkul\UVDesk\ExtensionFrameworkBundle\Utils\PackageCollection
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Utils\\PackageCollection'] = $container->createProxy('PackageCollection_b86d16c', function () use ($container) {
                return \PackageCollection_b86d16c::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/extension-framework/Utils/PackageCollection.php';

        $instance = new \Webkul\UVDesk\ExtensionFrameworkBundle\Utils\PackageCollection($container, ($container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] ?? ($container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Definition\MappingResource())));

        $instance->organizeCollection();

        return $instance;
    }
}
