<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreparedResponseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\AutomationBundle\Controller\Automations\PreparedResponse' shared autowired service.
     *
     * @return \Webkul\UVDesk\AutomationBundle\Controller\Automations\PreparedResponse
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Controller/Automations/PreparedResponse.php';

        $container->services['Webkul\\UVDesk\\AutomationBundle\\Controller\\Automations\\PreparedResponse'] = $instance = new \Webkul\UVDesk\AutomationBundle\Controller\Automations\PreparedResponse(($container->services['user.service'] ?? $container->getUser_ServiceService()), ($container->services['translator'] ?? $container->getTranslatorService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\AutomationBundle\\Controller\\Automations\\PreparedResponse', $container));

        return $instance;
    }
}
