<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\CoreFrameworkBundle\Controller\Report' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Controller\Report
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Controller/Report.php';

        $container->services['Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Report'] = $instance = new \Webkul\UVDesk\CoreFrameworkBundle\Controller\Report(($container->services['user.service'] ?? $container->getUser_ServiceService()), ($container->services['uvdesk.service'] ?? $container->getUvdesk_ServiceService()), ($container->services['report.service'] ?? $container->load('getReport_ServiceService')), ($container->services['knp_paginator'] ?? $container->load('getKnpPaginatorService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Report', $container));

        return $instance;
    }
}
