<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRenderDashboardRoutineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine' shared autowired service.
     *
     * @return \Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/psr/event-dispatcher/src/StoppableEventInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/event-dispatcher-contracts/Event.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/extension-framework/Application/RoutineInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/extension-framework/Application/Routine/RenderDashboardRoutine.php';

        return $container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Application\\Routine\\RenderDashboardRoutine'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\RenderDashboardRoutine(($container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Dashboard\\DashboardTemplate'] ?? $container->getDashboardTemplateService()));
    }
}
