<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\ApiBundle\API\Sessions' shared autowired service.
     *
     * @return \Webkul\UVDesk\ApiBundle\API\Sessions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/api-bundle/API/Sessions.php';

        $container->services['Webkul\\UVDesk\\ApiBundle\\API\\Sessions'] = $instance = new \Webkul\UVDesk\ApiBundle\API\Sessions();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\ApiBundle\\API\\Sessions', $container));

        return $instance;
    }
}
