<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_ManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authentication.manager' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager
     *
     * @deprecated Since symfony/security-bundle 5.3: The "security.authentication.manager" service is deprecated, use the new authenticator system instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/security-bundle', '5.3', 'The "security.authentication.manager" service is deprecated, use the new authenticator system instead.');

        $container->privates['security.authentication.manager'] = $instance = new \Symfony\Component\Security\Core\Authentication\AuthenticationProviderManager(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.authentication.provider.dao.back_support'] ?? $container->load('getSecurity_Authentication_Provider_Dao_BackSupportService'));
            yield 1 => ($container->privates['security.authentication.provider.rememberme.back_support'] ?? $container->load('getSecurity_Authentication_Provider_Rememberme_BackSupportService'));
            yield 2 => ($container->privates['security.authentication.provider.anonymous.back_support'] ?? $container->load('getSecurity_Authentication_Provider_Anonymous_BackSupportService'));
            yield 3 => ($container->privates['security.authentication.provider.guard.uvdesk_api'] ?? $container->load('getSecurity_Authentication_Provider_Guard_UvdeskApiService'));
            yield 4 => ($container->privates['security.authentication.provider.anonymous.uvdesk_api'] ?? $container->load('getSecurity_Authentication_Provider_Anonymous_UvdeskApiService'));
            yield 5 => ($container->privates['security.authentication.provider.dao.customer'] ?? $container->load('getSecurity_Authentication_Provider_Dao_CustomerService'));
            yield 6 => ($container->privates['security.authentication.provider.anonymous.customer'] ?? $container->load('getSecurity_Authentication_Provider_Anonymous_CustomerService'));
        }, 7), true);

        $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));

        return $instance;
    }
}
