<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicketVoterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'debug.security.voter.Webkul\UVDesk\CoreFrameworkBundle\Security\TicketVoter' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/VoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/CacheableVoterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/TraceableVoter.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/Authorization/Voter/Voter.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Security/TicketVoter.php';

        $a = ($container->privates['debug.security.access.decision_manager'] ?? $container->getDebug_Security_Access_DecisionManagerService());

        if (isset($container->privates['debug.security.voter.Webkul\\UVDesk\\CoreFrameworkBundle\\Security\\TicketVoter'])) {
            return $container->privates['debug.security.voter.Webkul\\UVDesk\\CoreFrameworkBundle\\Security\\TicketVoter'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['debug.security.voter.Webkul\\UVDesk\\CoreFrameworkBundle\\Security\\TicketVoter'])) {
            return $container->privates['debug.security.voter.Webkul\\UVDesk\\CoreFrameworkBundle\\Security\\TicketVoter'];
        }

        return $container->privates['debug.security.voter.Webkul\\UVDesk\\CoreFrameworkBundle\\Security\\TicketVoter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(new \Webkul\UVDesk\CoreFrameworkBundle\Security\TicketVoter($container, $a), $b);
    }
}
