<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicket3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\SupportCenterBundle\Form\Ticket' shared autowired service.
     *
     * @return \Webkul\UVDesk\SupportCenterBundle\Form\Ticket
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/support-center-bundle/Form/Ticket.php';

        return $container->privates['Webkul\\UVDesk\\SupportCenterBundle\\Form\\Ticket'] = new \Webkul\UVDesk\SupportCenterBundle\Form\Ticket();
    }
}
