<?php

namespace ContainerMXwuYOs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUvdesk_Automations_WorkflowsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'uvdesk.automations.workflows' shared autowired service.
     *
     * @return \Webkul\UVDesk\AutomationBundle\EventListener\WorkflowListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/EventListener/WorkflowListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/event-dispatcher/src/StoppableEventInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/event-dispatcher-contracts/Event.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Event.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Events/AgentActivity.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Agent/Create.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Agent/Delete.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Agent/ForgotPassword.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Agent/Update.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Events/CustomerActivity.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Customer/Create.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Customer/Delete.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Customer/ForgotPassword.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Customer/Update.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Events/TicketActivity.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Agent.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/AgentReply.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Collaborator.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/CollaboratorReply.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Create.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/CustomerReply.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Delete.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Group.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Note.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Priority.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Status.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Team.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/ThreadUpdate.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/Ticket/Type.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Events/UserActivity.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Events/User/ForgotPassword.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Events/EmailActivity.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/mailbox-component/Workflow/Events/Email/EmailRecieved.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/automation-bundle/Workflow/Action.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Agent/MailAgent.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Agent/TransferTickets.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Customer/MailCustomer.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/AddNote.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailAgent.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailCustomer.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailGroup.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailLastCollaborator.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MailTeam.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/MarkSpam.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/RoundRobinTicketAssignment.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateAgent.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateGroup.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateLabel.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdatePriority.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateStatus.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateTag.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateTeam.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/Ticket/UpdateType.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/core-framework/Workflow/Actions/User/MailUser.php';
        include_once \dirname(__DIR__, 4).'/vendor/uvdesk/mailbox-component/Workflow/Actions/Email/FromEmail.php';

        $a = ($container->services['ticket.service'] ?? $container->getTicket_ServiceService());

        if (isset($container->services['uvdesk.automations.workflows'])) {
            return $container->services['uvdesk.automations.workflows'];
        }
        $b = ($container->services['user.service'] ?? $container->getUser_ServiceService());

        if (isset($container->services['uvdesk.automations.workflows'])) {
            return $container->services['uvdesk.automations.workflows'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['uvdesk.automations.workflows'] = $instance = new \Webkul\UVDesk\AutomationBundle\EventListener\WorkflowListener($container, $c, $a, $b);

        $d = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Create($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Delete($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\ForgotPassword($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Update($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Create($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Delete($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\ForgotPassword($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Update($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Agent($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\AgentReply($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Collaborator($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\CollaboratorReply($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Create($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\CustomerReply($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Delete($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Group($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Note($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Priority($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Status($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Team($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\ThreadUpdate($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Type($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\User\ForgotPassword($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\MailboxBundle\Workflow\Events\Email\EmailRecieved($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Agent\MailAgent($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Agent\TransferTickets($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Customer\MailCustomer($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\AddNote($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailAgent($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailCustomer($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailGroup($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailLastCollaborator($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailTeam($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MarkSpam($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\RoundRobinTicketAssignment($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateAgent($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateGroup($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateLabel($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdatePriority($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateStatus($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateTag($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateTeam($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateType($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\User\MailUser($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\MailboxBundle\Workflow\Actions\Email\FromEmail($container, $d, $c));

        return $instance;
    }
}
