<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_HsfYii4_ClosureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hsfYii4.Closure' shared service.
     *
     * @return \Closure
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hsfYii4": it references class "Closure" but no such service exists. You should maybe alias this class to one of these existing services: "container.getenv", "data_collector.request.session_collector".');
    }
}
