<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VuNdeAYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vuNdeAY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vuNdeAY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailboxService' => ['privates', 'Webkul\\UVDesk\\MailboxBundle\\Services\\MailboxService', 'getMailboxServiceService', false],
            'swiftMailer' => ['services', 'swiftmailer.service', 'getSwiftmailer_ServiceService', false],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
            'userService' => ['services', 'user.service', 'getUser_ServiceService', false],
        ], [
            'entityManager' => '?',
            'mailboxService' => 'Webkul\\UVDesk\\MailboxBundle\\Services\\MailboxService',
            'swiftMailer' => '?',
            'translator' => '?',
            'userService' => '?',
        ]);
    }
}
