<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CDQF3rsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cDQF3rs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cDQF3rs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'container' => ['services', 'service_container', 'getServiceContainerService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'userService' => ['services', 'user.service', 'getUser_ServiceService', false],
        ], [
            'container' => '?',
            'entityManager' => '?',
            'eventDispatcher' => '?',
            'userService' => '?',
        ]);
    }
}
