<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiRoutineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\ApiRoutine' shared autowired service.
     *
     * @return \Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\ApiRoutine
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'psr'.\DIRECTORY_SEPARATOR.'event-dispatcher'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'StoppableEventInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'event-dispatcher-contracts'.\DIRECTORY_SEPARATOR.'Event.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'extension-framework'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'RoutineInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'extension-framework'.\DIRECTORY_SEPARATOR.'Application'.\DIRECTORY_SEPARATOR.'Routine'.\DIRECTORY_SEPARATOR.'ApiRoutine.php';

        return $container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Application\\Routine\\ApiRoutine'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Application\Routine\ApiRoutine(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
