<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuildExtensionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Webkul\UVDesk\ExtensionFrameworkBundle\Console\BuildExtensions' shared autowired service.
     *
     * @return \Webkul\UVDesk\ExtensionFrameworkBundle\Console\BuildExtensions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'extension-framework'.\DIRECTORY_SEPARATOR.'Console'.\DIRECTORY_SEPARATOR.'BuildExtensions.php';

        return $container->services['console.command.public_alias.Webkul\\UVDesk\\ExtensionFrameworkBundle\\Console\\BuildExtensions'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Console\BuildExtensions($container);
    }
}
