<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBootstrappingProjectService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Webkul\UVDesk\CoreFrameworkBundle\Guides\BootstrappingProject' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Guides\BootstrappingProject
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Guides'.\DIRECTORY_SEPARATOR.'BootstrappingProject.php';

        return $container->services['console.command.public_alias.Webkul\\UVDesk\\CoreFrameworkBundle\\Guides\\BootstrappingProject'] = new \Webkul\UVDesk\CoreFrameworkBundle\Guides\BootstrappingProject();
    }
}
