<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomer2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\SupportCenterBundle\Controller\Customer' shared autowired service.
     *
     * @return \Webkul\UVDesk\SupportCenterBundle\Controller\Customer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'support-center-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Customer.php';

        $container->services['Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Customer'] = $instance = new \Webkul\UVDesk\SupportCenterBundle\Controller\Customer(($container->services['translator'] ?? $container->getTranslatorService()), ($container->services['.container.private.security.password_encoder'] ?? $container->load('get_Container_Private_Security_PasswordEncoderService')), ($container->services['uvdesk.core.file_system.service'] ?? $container->getUvdesk_Core_FileSystem_ServiceService()), ($container->privates['Webkul\\UVDesk\\CoreFrameworkBundle\\Services\\FileUploadService'] ?? $container->getFileUploadServiceService()), ($container->services['email.service'] ?? $container->getEmail_ServiceService()), ($container->services['uvdesk.service'] ?? $container->getUvdesk_ServiceService()), ($container->services['user.provider'] ?? $container->load('getUser_ProviderService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\SupportCenterBundle\\Controller\\Customer', $container));

        return $instance;
    }
}
