<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCustomersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\ApiBundle\API\Customers' shared autowired service.
     *
     * @return \Webkul\UVDesk\ApiBundle\API\Customers
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'api-bundle'.\DIRECTORY_SEPARATOR.'API'.\DIRECTORY_SEPARATOR.'Customers.php';

        $container->services['Webkul\\UVDesk\\ApiBundle\\API\\Customers'] = $instance = new \Webkul\UVDesk\ApiBundle\API\Customers();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\ApiBundle\\API\\Customers', $container));

        return $instance;
    }
}
