<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\ExtensionFrameworkBundle\EventListener\Console' shared autowired service.
     *
     * @return \Webkul\UVDesk\ExtensionFrameworkBundle\EventListener\Console
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'extension-framework'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'Console.php';

        return $container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\EventListener\\Console'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\EventListener\Console($container, ($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] ?? ($container->privates['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Definition\\MappingResource'] = new \Webkul\UVDesk\ExtensionFrameworkBundle\Definition\MappingResource())));
    }
}
