<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Console\Wizard\DefaultUser' shared autowired service.
     *
     * @return \App\Console\Wizard\DefaultUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Console'.\DIRECTORY_SEPARATOR.'Wizard'.\DIRECTORY_SEPARATOR.'DefaultUser.php';

        return $container->services['console.command.public_alias.App\\Console\\Wizard\\DefaultUser'] = new \App\Console\Wizard\DefaultUser($container, ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['.container.private.security.password_encoder'] ?? $container->load('get_Container_Private_Security_PasswordEncoderService')));
    }
}
