<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Dashboard' shared autowired service.
     *
     * @return \Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Dashboard
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'extension-framework'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Dashboard.php';

        $container->services['Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Dashboard'] = $instance = new \Webkul\UVDesk\ExtensionFrameworkBundle\Controller\Dashboard();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\ExtensionFrameworkBundle\\Controller\\Dashboard', $container));

        return $instance;
    }
}
