<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnvironmentVariablesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.App\Console\EnvironmentVariables' shared autowired service.
     *
     * @return \App\Console\EnvironmentVariables
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Console'.\DIRECTORY_SEPARATOR.'EnvironmentVariables.php';

        return $container->services['console.command.public_alias.App\\Console\\EnvironmentVariables'] = new \App\Console\EnvironmentVariables($container);
    }
}
