<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageCacheControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImageCache\ImageCacheController' shared autowired service.
     *
     * @return \App\Controller\ImageCache\ImageCacheController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ImageCache'.\DIRECTORY_SEPARATOR.'ImageCacheController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UrlImageCacheService.php';

        $container->services['App\\Controller\\ImageCache\\ImageCacheController'] = $instance = new \App\Controller\ImageCache\ImageCacheController(new \App\Service\UrlImageCacheService($container));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ImageCache\\ImageCacheController', $container));

        return $instance;
    }
}
