<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ImageCache\ImageManager' shared autowired service.
     *
     * @return \App\Controller\ImageCache\ImageManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'intervention'.\DIRECTORY_SEPARATOR.'image'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Intervention'.\DIRECTORY_SEPARATOR.'Image'.\DIRECTORY_SEPARATOR.'ImageManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ImageCache'.\DIRECTORY_SEPARATOR.'ImageManager.php';

        return $container->services['App\\Controller\\ImageCache\\ImageManager'] = new \App\Controller\ImageCache\ImageManager($container);
    }
}
