<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKernelExceptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\ApiBundle\EventListeners\API\KernelException' shared autowired service.
     *
     * @return \Webkul\UVDesk\ApiBundle\EventListeners\API\KernelException
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'api-bundle'.\DIRECTORY_SEPARATOR.'EventListeners'.\DIRECTORY_SEPARATOR.'API'.\DIRECTORY_SEPARATOR.'KernelException.php';

        $a = ($container->privates['security.firewall.map'] ?? $container->getSecurity_Firewall_MapService());

        if (isset($container->privates['Webkul\\UVDesk\\ApiBundle\\EventListeners\\API\\KernelException'])) {
            return $container->privates['Webkul\\UVDesk\\ApiBundle\\EventListeners\\API\\KernelException'];
        }

        return $container->privates['Webkul\\UVDesk\\ApiBundle\\EventListeners\\API\\KernelException'] = new \Webkul\UVDesk\ApiBundle\EventListeners\API\KernelException($a);
    }
}
