<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMicrosoftAppsXHRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\CoreFrameworkBundle\Controller\Microsoft\MicrosoftAppsXHR' shared autowired service.
     *
     * @return \Webkul\UVDesk\CoreFrameworkBundle\Controller\Microsoft\MicrosoftAppsXHR
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Microsoft'.\DIRECTORY_SEPARATOR.'MicrosoftAppsXHR.php';

        $container->services['Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Microsoft\\MicrosoftAppsXHR'] = $instance = new \Webkul\UVDesk\CoreFrameworkBundle\Controller\Microsoft\MicrosoftAppsXHR();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\CoreFrameworkBundle\\Controller\\Microsoft\\MicrosoftAppsXHR', $container));

        return $instance;
    }
}
