<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreparedResponseXHRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Webkul\UVDesk\AutomationBundle\Controller\Automations\PreparedResponseXHR' shared autowired service.
     *
     * @return \Webkul\UVDesk\AutomationBundle\Controller\Automations\PreparedResponseXHR
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Automations'.\DIRECTORY_SEPARATOR.'PreparedResponseXHR.php';

        $container->services['Webkul\\UVDesk\\AutomationBundle\\Controller\\Automations\\PreparedResponseXHR'] = $instance = new \Webkul\UVDesk\AutomationBundle\Controller\Automations\PreparedResponseXHR(($container->services['user.service'] ?? $container->getUser_ServiceService()), ($container->services['uvdesk.automations.prepared_responses'] ?? $container->load('getUvdesk_Automations_PreparedResponsesService')), ($container->services['translator'] ?? $container->getTranslatorService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Webkul\\UVDesk\\AutomationBundle\\Controller\\Automations\\PreparedResponseXHR', $container));

        return $instance;
    }
}
