<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Listener_Form_BackSupportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authentication.listener.form.back_support' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\UsernamePasswordFormAuthenticationListener
     *
     * @deprecated Since symfony/security-bundle 5.3: The "security.authentication.listener.form.back_support" service is deprecated, use the new authenticator system instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/security-bundle', '5.3', 'The "security.authentication.listener.form.back_support" service is deprecated, use the new authenticator system instead.');

        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'AuthenticationSuccessHandlerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'TargetPathTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'DefaultAuthenticationSuccessHandler.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'AuthenticationFailureHandlerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'DefaultAuthenticationFailureHandler.php';

        $a = ($container->privates['security.authentication.manager'] ?? $container->load('getSecurity_Authentication_ManagerService'));

        if (isset($container->privates['security.authentication.listener.form.back_support'])) {
            return $container->privates['security.authentication.listener.form.back_support'];
        }
        $b = ($container->services['http_kernel'] ?? $container->getHttpKernelService());

        if (isset($container->privates['security.authentication.listener.form.back_support'])) {
            return $container->privates['security.authentication.listener.form.back_support'];
        }
        $c = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['security.authentication.listener.form.back_support'])) {
            return $container->privates['security.authentication.listener.form.back_support'];
        }
        $d = ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService'));
        $e = new \Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler($d, [], ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
        $e->setOptions(['use_referer' => true, 'login_path' => 'helpdesk_member_handle_login', 'default_target_path' => 'helpdesk_member_dashboard', 'always_use_default_target_path' => true, 'target_path_parameter' => '_target_path']);
        $e->setFirewallName('back_support');
        $f = ($container->privates['monolog.logger.security'] ?? $container->load('getMonolog_Logger_SecurityService'));

        $g = new \Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler($b, $d, [], $f);
        $g->setOptions(['login_path' => 'helpdesk_member_handle_login', 'failure_path' => NULL, 'failure_forward' => false, 'failure_path_parameter' => '_failure_path']);

        $container->privates['security.authentication.listener.form.back_support'] = $instance = new \Symfony\Component\Security\Http\Firewall\UsernamePasswordFormAuthenticationListener(($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), $a, ($container->privates['security.authentication.session_strategy'] ?? $container->load('getSecurity_Authentication_SessionStrategyService')), $d, 'back_support', $e, $g, ['login_path' => 'helpdesk_member_handle_login', 'check_path' => 'helpdesk_member_handle_login', 'use_forward' => false, 'require_previous_session' => false, 'username_parameter' => '_username', 'password_parameter' => '_password', 'csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'authenticate', 'enable_csrf' => false, 'post_only' => true, 'form_only' => false], $f, $c, NULL);

        $instance->setRememberMeServices(($container->privates['security.authentication.rememberme.services.simplehash.back_support'] ?? $container->load('getSecurity_Authentication_Rememberme_Services_Simplehash_BackSupportService')));

        return $instance;
    }
}
