<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTicket3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Webkul\UVDesk\SupportCenterBundle\Form\Ticket' shared autowired service.
     *
     * @return \Webkul\UVDesk\SupportCenterBundle\Form\Ticket
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'support-center-bundle'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Ticket.php';

        return $container->privates['Webkul\\UVDesk\\SupportCenterBundle\\Form\\Ticket'] = new \Webkul\UVDesk\SupportCenterBundle\Form\Ticket();
    }
}
