<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUvdesk_Automations_WorkflowsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'uvdesk.automations.workflows' shared autowired service.
     *
     * @return \Webkul\UVDesk\AutomationBundle\EventListener\WorkflowListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'WorkflowListener.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'psr'.\DIRECTORY_SEPARATOR.'event-dispatcher'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'StoppableEventInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'event-dispatcher-contracts'.\DIRECTORY_SEPARATOR.'Event.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Event.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'AgentActivity.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Agent'.\DIRECTORY_SEPARATOR.'Create.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Agent'.\DIRECTORY_SEPARATOR.'Delete.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Agent'.\DIRECTORY_SEPARATOR.'ForgotPassword.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Agent'.\DIRECTORY_SEPARATOR.'Update.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'CustomerActivity.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Customer'.\DIRECTORY_SEPARATOR.'Create.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Customer'.\DIRECTORY_SEPARATOR.'Delete.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Customer'.\DIRECTORY_SEPARATOR.'ForgotPassword.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Customer'.\DIRECTORY_SEPARATOR.'Update.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'TicketActivity.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Agent.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'AgentReply.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Collaborator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'CollaboratorReply.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Create.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'CustomerReply.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Delete.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Group.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Note.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Priority.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Status.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Team.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'ThreadUpdate.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Type.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'UserActivity.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'ForgotPassword.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'EmailActivity.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'mailbox-component'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'EmailRecieved.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Action.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Agent'.\DIRECTORY_SEPARATOR.'MailAgent.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Agent'.\DIRECTORY_SEPARATOR.'TransferTickets.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Customer'.\DIRECTORY_SEPARATOR.'MailCustomer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'AddNote.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailAgent.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailCustomer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailGroup.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailLastCollaborator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailTeam.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MarkSpam.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'RoundRobinTicketAssignment.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateAgent.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateGroup.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateLabel.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdatePriority.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateStatus.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateTag.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateTeam.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'MailUser.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'mailbox-component'.\DIRECTORY_SEPARATOR.'Workflow'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Email'.\DIRECTORY_SEPARATOR.'FromEmail.php';

        $a = ($container->services['ticket.service'] ?? $container->getTicket_ServiceService());

        if (isset($container->services['uvdesk.automations.workflows'])) {
            return $container->services['uvdesk.automations.workflows'];
        }
        $b = ($container->services['user.service'] ?? $container->getUser_ServiceService());

        if (isset($container->services['uvdesk.automations.workflows'])) {
            return $container->services['uvdesk.automations.workflows'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['uvdesk.automations.workflows'] = $instance = new \Webkul\UVDesk\AutomationBundle\EventListener\WorkflowListener($container, $c, $a, $b);

        $d = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Create($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Delete($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\ForgotPassword($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Agent\Update($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Create($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Delete($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\ForgotPassword($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Customer\Update($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Agent($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\AgentReply($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Collaborator($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\CollaboratorReply($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Create($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\CustomerReply($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Delete($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Group($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Note($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Priority($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Status($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Team($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\ThreadUpdate($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\Ticket\Type($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Events\User\ForgotPassword($container, $d, $c));
        $instance->registerWorkflowEvent(new \Webkul\UVDesk\MailboxBundle\Workflow\Events\Email\EmailRecieved($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Agent\MailAgent($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Agent\TransferTickets($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Customer\MailCustomer($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\AddNote($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailAgent($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailCustomer($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailGroup($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailLastCollaborator($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MailTeam($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\MarkSpam($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\RoundRobinTicketAssignment($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateAgent($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateGroup($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateLabel($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdatePriority($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateStatus($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateTag($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateTeam($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\Ticket\UpdateType($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\CoreFrameworkBundle\Workflow\Actions\User\MailUser($container, $d, $c));
        $instance->registerWorkflowAction(new \Webkul\UVDesk\MailboxBundle\Workflow\Actions\Email\FromEmail($container, $d, $c));

        return $instance;
    }
}
