<?php

namespace ContainerC8TILeQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUvdesk_Automations_PreparedResponsesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'uvdesk.automations.prepared_responses' shared autowired service.
     *
     * @return \Webkul\UVDesk\AutomationBundle\EventListener\PreparedResponseListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'PreparedResponseListener.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'automation-bundle'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Action.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Agent'.\DIRECTORY_SEPARATOR.'MailAgent.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Agent'.\DIRECTORY_SEPARATOR.'TransferTickets.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Customer'.\DIRECTORY_SEPARATOR.'MailCustomer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'AddNote.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'Delete.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailAgent.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailCustomer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailGroup.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailLastCollaborator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MailTeam.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'MarkSpam.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateAgent.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateGroup.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdatePriority.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateStatus.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateTag.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateTeam.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'uvdesk'.\DIRECTORY_SEPARATOR.'core-framework'.\DIRECTORY_SEPARATOR.'PreparedResponse'.\DIRECTORY_SEPARATOR.'Actions'.\DIRECTORY_SEPARATOR.'Ticket'.\DIRECTORY_SEPARATOR.'UpdateType.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        $container->services['uvdesk.automations.prepared_responses'] = $instance = new \Webkul\UVDesk\AutomationBundle\EventListener\PreparedResponseListener($container, $a);

        $b = ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack()));

        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Agent\MailAgent($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Agent\TransferTickets($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Customer\MailCustomer($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\AddNote($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\Delete($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\MailAgent($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\MailCustomer($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\MailGroup($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\MailLastCollaborator($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\MailTeam($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\MarkSpam($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\UpdateAgent($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\UpdateGroup($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\UpdatePriority($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\UpdateStatus($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\UpdateTag($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\UpdateTeam($container, $b, $a));
        $instance->registerPreparedResponseAction(new \Webkul\UVDesk\CoreFrameworkBundle\PreparedResponse\Actions\Ticket\UpdateType($container, $b, $a));

        return $instance;
    }
}
