<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMXwuYOs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMXwuYOs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMXwuYOs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMXwuYOs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMXwuYOs\App_KernelDevDebugContainer([
    'container.build_hash' => 'MXwuYOs',
    'container.build_id' => '042d502c',
    'container.build_time' => 1758535847,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMXwuYOs');
